### ISSUE TITLE
Nacitanie modelu pre LocalAreas

### ISSUE THREAD

**Issue by ZueFe** [fRandOmizer/Thesis#3]
BatchComparionResults:2373 -- vzdy sa berie len prvy model, to nemusi byt (a by default nie je) model, ktory je vizualizovany. By default je vizualizovany Avg Model - CSV vysledky k nemu najdes cez bc.getHd() kde bc je instancia BatchComparison 

Rovnako tak  GetAuxiliaryResults() nevracia to co potrebujes. Pre Avg Model su potrebne vysledky v bc.getHd(), pokial je zvoleny iny model ako avg, tak nacitaj vsetky data pomocou FileUtils.instance().readFolderWithCSV() -- cestu k ulozenym datam najdes v instancii BatchComparison pod hdCSVresults (odkaz ku zlozke), cela cesta pre model s indexom 2:

hdCSVresults + File.separator + 2
(pokial by to nahodou nefungovalo tak skus : hdCSVresults + File.separator + (2+1))

to ti vrati List<List<Float>> z ktoreho potrebujes ziskat konecny vysledok za pomoci metody

SurfaceComparisonProcessing.instance().computeVariation()

ten potom podhodit vypoctu ploch

Nasledne v LocalAreasJPanel:61 by sa mal teda pouzivat konecny vysledok.

**Comment by fRandOmizer** [comment]
Vyriesene + mensi upgrade co sa tyka rozsahu povolenych hodnot.
